//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(AsignacionMetadata))]
    public partial class Asignacion
    {
        public int Id { get; set; }
        public int IdResidencia { get; set; }
        public int IdPlan { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string EstadoCuenta { get; set; }
        public bool Deuda { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Residencia Residencia { get; set; }
    }
}
