//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion
    {
        public int Id { get; set; }
        public int IdResidencia { get; set; }
        public int IdPlan { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string EstadoCuenta { get; set; }
        public bool Deuda { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Residencia Residencia { get; set; }
    }
}
