//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(AvisosMetadata))]

    public partial class Avisos
    {
        public int id { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string Descripcion { get; set; }
        public string TipoAviso { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte[] Documento { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
