//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CondominionsEntities : DbContext
    {
        public CondominionsEntities()
            : base("name=CondominionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaComun> AreaComun { get; set; }
        public virtual DbSet<Asignacion> Asignacion { get; set; }
        public virtual DbSet<Avisos> Avisos { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Residencia> Residencia { get; set; }
        public virtual DbSet<Rubro> Rubro { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Visitante> Visitante { get; set; }
    }
}
