//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime HoraInicio { get; set; }
        public System.DateTime HoraFin { get; set; }
        public bool Estado { get; set; }
        public int idArea { get; set; }
        public int Total { get; set; }
    
        public virtual AreaComun AreaComun { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
