//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitante
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Apelido { get; set; }
        public int Telefono { get; set; }
        public System.DateTime FechaVisita { get; set; }
        public int idResidencia { get; set; }
    
        public virtual Residencia Residencia { get; set; }
    }
}
