//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(VisitanteMetadata))]
    public partial class Visitante
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Apelido { get; set; }
        public int Telefono { get; set; }
        public System.DateTime FechaVisita { get; set; }
        public int idResidencia { get; set; }
    
        public virtual Residencia Residencia { get; set; }
    }
}
